### ISSUE TITLE
Where is the bookgen/generate.js

### ISSUE THREAD

**Issue by shnode** [mixu/singlepageappbook#28]
Sorry to bother you, but where is the generate.js ?

**Comment by mixu** [comment]
ah I updated this to use [markdown-styles](https://github.com/mixu/markdown-styles) so you should just run `make book` after `npm install -g markdown-styles` (e.g. see the Makefile).

**Comment by shnode** [comment]
Thank you! I'm gonna translate your book into Chinese.
